# Generated by Django 5.1 on 2026-03-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('booking_date', models.DateField(verbose_name='Дата записи')),
                ('booking_time', models.TimeField(verbose_name='Время записи')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ориентировочная стоимость')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client', verbose_name='Клиент')),
                ('services', models.ManyToManyField(blank=True, related_name='bookings', to='services.service', verbose_name='Услуги')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.vehicle', verbose_name='Автомобиль')),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='orders.workorder', verbose_name='Заказ-наряд')),
            ],
            options={
                'verbose_name': 'Запись на обслуживание',
                'verbose_name_plural': 'Записи на обслуживание',
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
    ]
