[pytest]
DJANGO_SETTINGS_MODULE = autoservice.settings.dev
python_files = tests/*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=accounts --cov=clients --cov=orders --cov=services --cov=notifications --cov=dashboard --cov=portal --cov-report=term-missing --cov-report=html
