# Generated by Django 5.2.12 on 2026-03-30 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='VIN должен содержать ровно 17 символов (латинские буквы и цифры) или быть пустым.', regex='^([A-HJ-NPR-Z0-9]{17})?$')], verbose_name='VIN-код'),
        ),
    ]
