# Generated by Django 5.1 on 2026-03-30 21:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('diagnostics', 'Диагностика'), ('approved', 'Согласован с клиентом'), ('in_progress', 'В работе'), ('waiting_parts', 'Ожидает запчасти'), ('completed', 'Выполнен'), ('ready', 'Готов к выдаче'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('total_services_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма услуг')),
                ('total_parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма запчастей')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Скидка (%)')),
                ('final_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого со скидкой')),
                ('estimated_completion', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая дата готовности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдан')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR-код')),
                ('assigned_mechanic', models.ForeignKey(blank=True, limit_choices_to={'role': 'mechanic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='Клиент')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Услуга')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.workorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Услуга в заказе',
                'verbose_name_plural': 'Услуги в заказе',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.sparepart', verbose_name='Запчасть')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='orders.workorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Запчасть в заказе',
                'verbose_name_plural': 'Запчасти в заказе',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(max_length=20, verbose_name='В статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.workorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-created_at'],
            },
        ),
    ]
