# Generated by Django 5.1 on 2026-03-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=20, verbose_name='Канал')),
                ('event_type', models.CharField(max_length=30, verbose_name='Тип события')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.client', verbose_name='Клиент')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.workorder', verbose_name='Заказ-наряд')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('event_type', models.CharField(choices=[('order_created', 'Заказ создан'), ('status_changed', 'Статус изменён'), ('order_ready', 'Заказ готов к выдаче'), ('order_delivered', 'Заказ выдан'), ('maintenance_reminder', 'Напоминание о ТО'), ('custom', 'Пользовательское')], max_length=30, verbose_name='Тип события')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=20, verbose_name='Канал')),
                ('subject_template', models.CharField(blank=True, max_length=200, verbose_name='Тема (для email)')),
                ('body_template', models.TextField(help_text='Переменные: {client_name}, {vehicle_info}, {order_number}, {status}, {total_cost}, {qr_url}, {workshop_phone}', verbose_name='Шаблон текста')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'ordering': ['event_type', 'channel'],
                'unique_together': {('event_type', 'channel')},
            },
        ),
    ]
